### ISSUE TITLE
Security issues found

### ISSUE THREAD

**Issue by OmgImAlexis** [SimonFair/unraid.usbip-gui#1]
Hi where should I report a security issue I've found?

**Comment by SimonFair** [comment]
Can you DM me on the forum SimonF This will be depreciated, does the same issue exist in USB_Manager which is the replacement.

**Comment by OmgImAlexis** [comment]
Can you please link me to the updated repo?

**Comment by OmgImAlexis** [comment]
@SimonFair found the repo, the issue is also present there. I'll send you a forum DM.
